swagger: '2.0'
info:
  description: |
    This is a simple Date microservice.
  version: 1.0.0
  title: swagger Date
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: Date
  description: Everything about your Date
# schemes:
# - http
paths:
  /date:
    get:
      tags:
      - Date
      summary: Get the next 10 working dates
      description: Returns next 10 Dates from today as a list
      operationId: getDates
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Dates'
        404:
          description: Date not found

    post:
      tags:
      - Date
      summary: Add a new Date
      operationId: addDate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Date string that needs to be added
        required: true
        schema:
          type: string
      responses:
        200:
          description: Date successfully created
        405:
          description: Invalid input
    put:
      tags:
      - Date
      summary: Update an existing Date
      operationId: updateDate
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Date object that needs to be updated
        required: true
        schema:
          $ref: '#/definitions/Date'
      responses:
        200:
          description: Date successfully updated
        400:
          description: Invalid ID supplied
        404:
          description: Date not found
        405:
          description: Validation exception
  /date/{dateId}:
    get:
      tags:
      - Date
      summary: Find Date by ID
      description: Returns a single Date
      operationId: getDateById
      produces:
      - application/json
      parameters:
      - name: dateId
        in: path
        description: ID of Date to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Date'
        400:
          description: Invalid ID supplied
        404:
          description: Tag not found
    delete:
      tags:
      - Date
      summary: Deletes a Date
      operationId: deleteDate
      produces:
      - application/json
      - application/xml
      parameters:
      - name: dateId
        in: path
        description: Date id to delete
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: Date not found

definitions:
  Date:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Dates:
    type: array
    items:
      type: string



# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /Personal3192/Date/1.0.0
schemes:
 - https
 - http
# Added by API Auto Mocking Plugin
# basePath: /ozgurakan/test/1.0.0
# Added by API Auto Mocking Plugin
basePath: /Personal3192/Date/1.0.0
