swagger: '2.0'
info:
  description: |
    This is a simple Projects microservice.
  version: 1.0.0
  title: swagger Projects
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: project
  description: Everything about your Projects
# schemes:
# - http
paths:
  /projects:
    get:
      tags:
      - project
      summary: Get all available projects
      description: Returns projects as a list
      operationId: getProjects
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Projects'
        404:
          description: Projects not found

    post:
      tags:
      - project
      summary: Add a new project
      operationId: addProject
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Project string that needs to be added
        required: true
        schema:
          type: string
      responses:
        200:
          description: Project successfully created
        405:
          description: Invalid input
    put:
      tags:
      - project
      summary: Update an existing Project
      operationId: updateProject
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Project object that needs to be updated
        required: true
        schema:
          $ref: '#/definitions/Project'
      responses:
        200:
          description: Project successfully updated
        400:
          description: Invalid ID supplied
        404:
          description: Project not found
        405:
          description: Validation exception
  /projects/{projectId}:
    get:
      tags:
      - project
      summary: Find project by ID
      description: Returns a single Project
      operationId: getProjectById
      produces:
      - application/json
      parameters:
      - name: projectId
        in: path
        description: ID of Project to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Project'
        400:
          description: Invalid ID supplied
        404:
          description: Tag not found
    delete:
      tags:
      - project
      summary: Deletes a project
      operationId: deleteProject
      produces:
      - application/json
      - application/xml
      parameters:
      - name: projectId
        in: path
        description: Project id to delete
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: Project not found

definitions:
  Project:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Projects:
    type: array
    items:
      type: string



# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /Personal3192/Projects/1.0.0
schemes:
 - https
 - http
# Added by API Auto Mocking Plugin
# basePath: /ozgurakan/test/1.0.0
# Added by API Auto Mocking Plugin
basePath: /Personal3192/Projects/1.0.0
