swagger: '2.0'
info:
  description: |
    This is a simple Priorities microservice.
  version: 1.0.0
  title: swagger Priorities
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: priority
  description: Everything about your Priorities
# schemes:
# - http
paths:
  /priorities:
    get:
      tags:
      - priority
      summary: Get all available priorities
      description: Returns priorities as a list
      operationId: getPriorities
      produces:
      - application/json
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Priorities'
        404:
          description: Priorities not found

    post:
      tags:
      - priority
      summary: Add a new priority
      operationId: addPriority
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Priority string that needs to be added
        required: true
        schema:
          type: string
      responses:
        200:
          description: Priority successfully created
        405:
          description: Invalid input
    put:
      tags:
      - priority
      summary: Update an existing Priority
      operationId: updatePriority
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Priority object that needs to be updated
        required: true
        schema:
          $ref: '#/definitions/Priority'
      responses:
        200:
          description: Priority successfully updated
        400:
          description: Invalid ID supplied
        404:
          description: Priority not found
        405:
          description: Validation exception
  /priorities/{priorityId}:
    get:
      tags:
      - priority
      summary: Find priority by ID
      description: Returns a single Priority
      operationId: getPriorityById
      produces:
      - application/json
      parameters:
      - name: priorityId
        in: path
        description: ID of Priority to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Priority'
        400:
          description: Invalid ID supplied
        404:
          description: Tag not found
    delete:
      tags:
      - priority
      summary: Deletes a priority
      operationId: deletePriority
      produces:
      - application/json
      - application/xml
      parameters:
      - name: priorityId
        in: path
        description: Priority id to delete
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
        400:
          description: Invalid ID supplied
        404:
          description: Priority not found

definitions:
  Priority:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Priorities:
    type: array
    items:
      type: string



# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /Personal3192/Priorities/1.0.0
schemes:
 - https
 - http
# Added by API Auto Mocking Plugin
# basePath: /ozgurakan/test/1.0.0
# Added by API Auto Mocking Plugin
basePath: /Personal3192/Priorities/1.0.0
