swagger: '2.0'
info:
  description: |
    This is a simple Priority microservice.
  version: 1.0.0
  title: swagger Priority
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: priority
  description: Everything about your Priorities
# schemes:
# - http
paths:
  /priority:
    post:
      tags:
      - priority
      summary: Add a new priority
      operationId: addPriority
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: priority object that needs to be added
        required: true
        schema:
          $ref: '#/definitions/Priority'
      responses:
        405:
          description: Invalid input
    put:
      tags:
      - priority
      summary: Update an existing priority
      operationId: updatePriority
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Priority object that needs to be added
        required: true
        schema:
          $ref: '#/definitions/Priority'
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Priority not found
        405:
          description: Validation exception
  /priority/{priorityId}:
    get:
      tags:
      - priority
      summary: Find priority by ID
      description: Returns a single priority
      operationId: getPriorityById
      produces:
      - application/json
      parameters:
      - name: priorityId
        in: path
        description: ID of priority to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Priority'
        400:
          description: Invalid ID supplied
        404:
          description: Priority not found
    delete:
      tags:
      - priority
      summary: Deletes a priority
      operationId: deletePriority
      produces:
      - application/json
      - application/xml
      parameters:
      - name: priorityId
        in: path
        description: Priority id to delete
        required: true
        type: integer
        format: int64
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Priority not found

definitions:
  Priority:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Personal3192/Priorities/1.0.0
schemes:
 - https
 - http
