swagger: '2.0'
info:
  description: |
    This is a simple Skill microservice.
  version: 1.0.0
  title: swagger Skill
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: skill
  description: Everything about your Skills
# schemes:
# - http
paths:
  /skill:
    post:
      tags:
      - skill
      summary: Add a new skill
      operationId: addSkill
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: skill object that needs to be added
        required: true
        schema:
          $ref: '#/definitions/Skill'
      responses:
        405:
          description: Invalid input
    put:
      tags:
      - skill
      summary: Update an existing skill
      operationId: updateSkill
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Skill object that needs to be added
        required: true
        schema:
          $ref: '#/definitions/Skill'
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Skill not found
        405:
          description: Validation exception
  /skill/{skillId}:
    get:
      tags:
      - skill
      summary: Find skill by ID
      description: Returns a single skill
      operationId: getSkillById
      produces:
      - application/json
      parameters:
      - name: skillId
        in: path
        description: ID of skill to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Skill'
        400:
          description: Invalid ID supplied
        404:
          description: Skill not found
    delete:
      tags:
      - skill
      summary: Deletes a skill
      operationId: deleteSkill
      produces:
      - application/json
      - application/xml
      parameters:
      - name: skillId
        in: path
        description: Skill id to delete
        required: true
        type: integer
        format: int64
      responses:
        400:
          description: Invalid ID supplied
        404:
          description: Skill not found

definitions:
  Skill:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /Personal3192/Skills/1.0.0
schemes:
 - https
 - http
